package com.banquito.originacion.enums;

public enum EstadoSolicitudEnum {
    BORRADOR,
    DOCUMENTACION_CARGADA,
    DOCUMENTACION_VALIDADA,
    DOCUMENTACION_RECHAZADA,
    CONTRATO_CARGADO,
    CONTRATO_VALIDADO,
    CONTRATO_RECHAZADO,
    APROBADA,
    RECHAZADA,
    CANCELADA
} 